TYPE
	PWM_MODULE_STATUS_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1064" #3"16" *)
		UnderVoltageError : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1066" #3"14" *)
		VolatgeWarning : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1067" #3"14" *)
		OverVoltageError : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1068" #3"14" *)
		OvertempeatureError : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1069" #3"14" *)
	END_STRUCT;
	MTR_COMMAND_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1147" #3"16" *)
		command_sm : SM_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1150" #3"16" *)
		Start : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1152" #3"14" *)
		Stop : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1153" #3"14" *)
		Reset : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1154" #3"14" *)
	END_STRUCT;
	SM_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\..\Lib\Statelib.h" #2"21" #3"24" *)
		Step : UDINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\..\Lib\Statelib.h" #2"22" #3"23" *)
		oldStep : UDINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\..\Lib\Statelib.h" #2"23" #3"23" *)
		new : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\..\Lib\Statelib.h" #2"24" #3"24" *)
		ErrorStep : UINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\..\Lib\Statelib.h" #2"25" #3"32" *)
		Tmr1 : TON;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\..\Lib\Statelib.h" #2"26" #3"25" *)
		Text : STRING[51];	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\..\Lib\Statelib.h" #2"27" #3"27" *)
	END_STRUCT;
	PS_MISC_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1215" #3"16" *)
		Ramp : LCRRamp;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1217" #3"21" *)
	END_STRUCT;
	MTR_PARAMETERS_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1159" #3"16" *)
		SpeedSetpoint : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1161" #3"15" *)
		OnRampTime : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1162" #3"15" *)
		OffRampTime : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1163" #3"15" *)
		OnDelayTime : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1164" #3"15" *)
		OffDelayTime : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1165" #3"15" *)
		BoostLevel1SetPoint : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1167" #3"15" *)
		BoostLevel2SetPoint : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1168" #3"15" *)
	END_STRUCT;
	MTR_HARDWARE_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1085" #3"16" *)
		PeriodDurationPWM : UINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1087" #3"14" *)
		PulseWidthPWM : INT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1088" #3"13" *)
		Counter : INT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1089" #3"13" *)
		CurrentMeasurement : INT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1090" #3"13" *)
		PWMError : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1092" #3"14" *)
		CurrentError : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1093" #3"14" *)
		OverCurrentError : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1094" #3"14" *)
		ClearError : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1095" #3"14" *)
		StartCurrentMeasurement : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1097" #3"14" *)
		ResetEncoder : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1100" #3"14" *)
	END_STRUCT;
	MACHINE_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"865" #3"16" *)
		PrimaryPSType : Primary_PS_Type;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"868" #3"25" *)
		HotwirePSType : Hotwire_PS_Type;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"869" #3"25" *)
		ControlMode : Control_Mode;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"870" #3"22" *)
		RunMode : Run_Mode;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"872" #3"18" *)
		LoadDefaultsMode : Load_Defaults_Mode;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"873" #3"28" *)
		Boost1Type : Boost_Type;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"875" #3"16" *)
		Boost2Type : Boost_Type;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"876" #3"16" *)
		ErrorCode : UINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"878" #3"14" *)
		AckErrors : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"879" #3"14" *)
		EditMode : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"881" #3"14" *)
		EstopFault : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"882" #3"14" *)
		BoostLevel1Active : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"885" #3"10" *)
		BoostLevel2Active : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"886" #3"10" *)
		SystemNeedsReset : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"888" #3"10" *)
	END_STRUCT;
	MENU_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"845" #3"16" *)
		Counter : INT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"847" #3"13" *)
		MenuButton : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"848" #3"14" *)
		LastCounter : INT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"849" #3"13" *)
		Blink : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"850" #3"14" *)
		Edit : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"851" #3"14" *)
		DisplayCode : Display_Setting_Code;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"852" #3"30" *)
		MenuMode : Menu_Mode;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"854" #3"19" *)
		ArcDisplayBlinkEnable : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"856" #3"14" *)
		RemDisplayBlinkEnable : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"857" #3"14" *)
		WfDisplayBlinkEnable : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"858" #3"14" *)
		WpDisplayBlinkEnable : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"859" #3"14" *)
		HwDisplayBlinkEnable : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"860" #3"14" *)
	END_STRUCT;
	PS_COMMAND_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1226" #3"16" *)
		command_sm : SM_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1229" #3"16" *)
		Start : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1231" #3"14" *)
		Stop : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1232" #3"14" *)
		Reset : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1233" #3"14" *)
	END_STRUCT;
	PS_PARAMETERS_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1238" #3"16" *)
		AmpsSetpoint : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1240" #3"15" *)
		OnRampTime : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1241" #3"15" *)
		OffRampTime : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1242" #3"15" *)
		OnDelayTime : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1243" #3"15" *)
		OffDelayTime : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1244" #3"15" *)
		BoostLevel1SetPoint : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1246" #3"15" *)
		BoostLevel2SetPoint : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1247" #3"15" *)
	END_STRUCT;
	PS_HARDWARE_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1193" #3"16" *)
		AnologCommandVoltage : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1196" #3"15" *)
		Enable : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1197" #3"14" *)
	END_STRUCT;
	HARDWARE_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1074" #3"16" *)
		Inputs : ARRAY[0..31] OF BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1076" #3"14" *)
		Outputs : ARRAY[0..11] OF BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1077" #3"14" *)
		AnalogOutputs : ARRAY[0..3] OF INT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1078" #3"13" *)
		AnalogInputs : ARRAY[0..3] OF INT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1079" #3"13" *)
		PWM_Status : PWM_MODULE_STATUS_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1080" #3"31" *)
	END_STRUCT;
	PS_HARDWARE_CONFIG_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1202" #3"16" *)
		CalSlope : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1204" #3"15" *)
		CalOffset : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1205" #3"15" *)
		AmpsPerVoltCommand : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1206" #3"15" *)
		AmpsPerVoltFeedback : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1207" #3"15" *)
	END_STRUCT;
	USERVALUES_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"989" #3"16" *)
		WF_Speed : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"993" #3"15" *)
		WP_Freq : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"994" #3"15" *)
		ARC_Amps : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"995" #3"15" *)
		HW_Amps : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"996" #3"15" *)
		WF_Speed_Boost_Level_1 : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1001" #3"11" *)
		WF_Speed_Boost_Level_2 : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1002" #3"11" *)
		WP_Freq_Boost_Level_1 : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1004" #3"15" *)
		WP_Freq_Boost_Level_2 : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1005" #3"15" *)
		ARC_Amps_Boost_Level_1 : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1007" #3"15" *)
		ARC_Amps_Boost_Level_2 : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1008" #3"15" *)
		HW_Amps_Boost_Level_1 : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1010" #3"15" *)
		HW_Amps_Boost_Level_2 : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1011" #3"15" *)
		Boost1Type : Boost_Type;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1013" #3"20" *)
		Boost2Type : Boost_Type;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1014" #3"16" *)
		WF_On_Delay_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1017" #3"11" *)
		WP_On_Delay_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1018" #3"15" *)
		ARC_On_Delay_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1019" #3"15" *)
		HW_On_Delay_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1020" #3"15" *)
		WF_Off_Delay_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1022" #3"15" *)
		WP_Off_Delay_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1023" #3"15" *)
		HW_Off_Delay_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1024" #3"15" *)
		ARC_Off_Delay_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1025" #3"15" *)
		WF_On_Ramp_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1028" #3"11" *)
		WP_On_Ramp_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1029" #3"15" *)
		ARC_On_Ramp_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1030" #3"15" *)
		HW_On_Ramp_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1031" #3"15" *)
		WF_Off_Ramp_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1033" #3"15" *)
		WP_Off_Ramp_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1034" #3"15" *)
		HW_Off_Ramp_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1035" #3"15" *)
		ARC_Off_Ramp_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1036" #3"15" *)
		WF_Speed_Cal_Slope : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1040" #3"15" *)
		WF_Speed_Cal_Offset : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1041" #3"11" *)
		WP_Speed_Cal_Slope : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1043" #3"15" *)
		WP_Speed_Cal_Offset : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1044" #3"11" *)
		ARC_Amps_Cal_Slope : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1046" #3"15" *)
		ARC_Speed_Cal_Offset : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1047" #3"15" *)
		HW_Amps_Cal_Slope : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1049" #3"15" *)
		HW_Speed_Cal_Offset : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1050" #3"15" *)
		PrimaryPSType : Primary_PS_Type;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1053" #3"25" *)
		HotwirePSType : Hotwire_PS_Type;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1054" #3"25" *)
		ControlMode : Control_Mode;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1055" #3"22" *)
		RunMode : Run_Mode;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1056" #3"18" *)
		FirstTimeThrough : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1058" #3"14" *)
	END_STRUCT;
	MTR_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1173" #3"16" *)
		Hardware : MTR_HARDWARE_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1175" #3"26" *)
		Parameters : MTR_PARAMETERS_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1176" #3"28" *)
		Command : MTR_COMMAND_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1177" #3"25" *)
		Misc : MTR_MISC_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1178" #3"22" *)
		HardwareConfig : MTR_HARDWARE_CONFIG_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1180" #3"33" *)
		CurrentVelocity : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1183" #3"15" *)
		CommandVelocity : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1184" #3"15" *)
		Status : UINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1186" #3"14" *)
	END_STRUCT;
	PS_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1252" #3"16" *)
		Hardware : PS_HARDWARE_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1254" #3"25" *)
		Parameters : PS_PARAMETERS_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1255" #3"27" *)
		Command : PS_COMMAND_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1256" #3"24" *)
		Misc : PS_MISC_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1257" #3"21" *)
		HardwareConfig : PS_HARDWARE_CONFIG_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1259" #3"32" *)
		CurrentAmps : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1262" #3"15" *)
		CommandAmps : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1263" #3"15" *)
		Status : UINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1265" #3"14" *)
	END_STRUCT;
	MTR_HARDWARE_CONFIG_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1106" #3"16" *)
		CalSlope : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1109" #3"15" *)
		CalOffset : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1110" #3"15" *)
		EngUnit : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1112" #3"16" *)
		MtrDir : INT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1113" #3"16" *)
		CyclesInOvercurrent : UINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1117" #3"14" *)
		CyclesInOvercurrentLimit : UINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1119" #3"14" *)
		CurrentLimit : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1121" #3"15" *)
	END_STRUCT;
	MTR_MISC_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1127" #3"16" *)
		Ramp : LCRRamp;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1130" #3"21" *)
		PID : LCRSlimPID;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1135" #3"24" *)
		PIDParameters : lcrslimpid_par_typ;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1136" #3"28" *)
		LastPosition : INT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1138" #3"13" *)
		CurrentPosition : INT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1139" #3"13" *)
		DeltaPosition : DINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"1140" #3"14" *)
	END_STRUCT;
	bgRingBuffer_typ : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\..\Lib\utilityLib\bgringbuffer.h" #2"23" #3"16" *)
		bufSize : DINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\..\Lib\utilityLib\bgringbuffer.h" #2"25" #3"13" *)
		init : DINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\..\Lib\utilityLib\bgringbuffer.h" #2"26" #3"13" *)
		overrun : DINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\..\Lib\utilityLib\bgringbuffer.h" #2"27" #3"13" *)
		dbgLevel : DINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\..\Lib\utilityLib\bgringbuffer.h" #2"28" #3"13" *)
		dbgFormat : DINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\..\Lib\utilityLib\bgringbuffer.h" #2"29" #3"13" *)
		ptrCircularBufferBegin : UDINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\..\Lib\utilityLib\bgringbuffer.h" #2"31" #3"13" *)
		ptrCircularBufferEnd : UDINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\..\Lib\utilityLib\bgringbuffer.h" #2"32" #3"13" *)
		ptrDataIn : UDINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\..\Lib\utilityLib\bgringbuffer.h" #2"34" #3"13" *)
		ptrDataOut : UDINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\..\Lib\utilityLib\bgringbuffer.h" #2"35" #3"13" *)
	END_STRUCT;
END_TYPE
TYPE
	Primary_PS_Type :
 	(	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"644" #3"14" *)
		Miller_Type := 0,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"646" #3"9" *)
		GTII_Type := 1,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"647" #3"9" *)
		GTVI_Type := 2,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"648" #3"9" *)
		LINC_Type := 3	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"649" #3"9" *)
	);
	Boost_Type :
 	(	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"608" #3"14" *)
		ARC_Boost_Type := 0,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"610" #3"9" *)
		WF_Boost_Type := 1,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"611" #3"9" *)
		WP_Boost_Type := 2,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"612" #3"9" *)
		HW_Boost_Type := 3,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"613" #3"9" *)
		ARC_WF_Boost_Type := 4,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"614" #3"9" *)
		ARC_WP_Boost_Type := 5,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"615" #3"9" *)
		ARC_HW_Boost_Type := 6,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"616" #3"9" *)
		WF_WP_Boost_Type := 7,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"617" #3"9" *)
		WF_HW_Boost_Type := 8,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"618" #3"9" *)
		WP_HW_Boost_Mode := 9,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"619" #3"9" *)
		ARC_WF_WP_Boost_Type := 10,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"620" #3"9" *)
		ARC_WF_HW_Boost_Type := 11,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"621" #3"9" *)
		ARC_WP_HW_Boost_Type := 12,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"622" #3"9" *)
		WF_WP_HW_Boost_Type := 13,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"623" #3"9" *)
		ARC_WF_WP_HW_Boost_Type := 14	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"624" #3"9" *)
	);
	Display_Setting_Code :
 	(	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"492" #3"14" *)
		WpFreq_Setting := 0,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"494" #3"9" *)
		WfSpeed_Setting := 1,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"495" #3"9" *)
		ArcAmps_Setting := 2,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"496" #3"9" *)
		HwAmps_Setting := 3,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"497" #3"9" *)
		BoostLevel_1_Variable_Setting := 4,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"499" #3"9" *)
		ArcAmpsBoostLevel_1_Setting := 5,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"501" #3"9" *)
		WfSpeedBoostLevel_1_Setting := 6,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"502" #3"9" *)
		WpFreqBoostLevel_1_Setting := 7,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"503" #3"9" *)
		HwAmpsBoostLevel_1_Setting := 8,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"504" #3"9" *)
		BoostLevel_2_Variable_Setting := 9,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"506" #3"9" *)
		ArcAmpsBoostLevel_2_Setting := 10,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"508" #3"9" *)
		WfSpeedBoostLevel_2_Setting := 11,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"509" #3"9" *)
		WpFreqBoostLevel_2_Setting := 12,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"510" #3"9" *)
		HwAmpsBoostLevel_2_Setting := 13,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"511" #3"9" *)
		ArcStartDelay_Setting := 14,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"513" #3"9" *)
		WfStartDelay_Setting := 15,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"514" #3"9" *)
		WpStartDelay_Setting := 16,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"515" #3"9" *)
		HwStartDelay_Setting := 17,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"516" #3"9" *)
		ArcStopDelay_Setting := 18,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"518" #3"9" *)
		WfStopDelay_Setting := 19,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"519" #3"9" *)
		WpStopDelay_Setting := 20,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"520" #3"9" *)
		HwStopDelay_Setting := 21,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"521" #3"9" *)
		ArcStartRamp_Setting := 22,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"523" #3"9" *)
		WfStartRamp_Setting := 23,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"524" #3"9" *)
		WpStartRamp_Setting := 24,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"525" #3"9" *)
		HwStartRamp_Setting := 25,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"526" #3"9" *)
		ArcStopRamp_Setting := 26,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"528" #3"9" *)
		WfStopRamp_Setting := 27,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"529" #3"9" *)
		WpStopRamp_Setting := 28,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"530" #3"9" *)
		HwStopRamp_Setting := 29,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"531" #3"9" *)
		ArcCalSlope_Setting := 30,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"533" #3"9" *)
		WfCalSlope_Setting := 31,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"534" #3"9" *)
		HwCalSlope_Setting := 32,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"535" #3"9" *)
		ArcCalOffset_Setting := 33,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"537" #3"9" *)
		WfCalOffset_Setting := 34,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"538" #3"9" *)
		HwCalOffset_Setting := 35,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"539" #3"9" *)
		PrimaryPowerSupplyType_Setting := 36,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"541" #3"9" *)
		HotwirePowerSupplyType_Setting := 37,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"542" #3"9" *)
		ControlMode_Setting := 38,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"543" #3"9" *)
		RunMode_Setting := 39,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"544" #3"9" *)
		LoadDefaults_Setting := 40,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"546" #3"9" *)
		MenuMode_Setting := 41,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"548" #3"9" *)
		ErrorCode_Ack := 42,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"550" #3"9" *)
		PLC_Version := 43,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"552" #3"9" *)
		NEXT_Project_Setting := 44,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"554" #3"9" *)
		Last_Display_Setting_Code := 45	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"556" #3"9" *)
	);
	Run_Mode :
 	(	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"687" #3"14" *)
		WF_Mode := 0,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"689" #3"9" *)
		WP_Mode := 1,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"690" #3"9" *)
		HW_Mode := 2,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"691" #3"9" *)
		WF_And_WP_Mode := 3,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"692" #3"9" *)
		WF_And_HW_Mode := 4,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"693" #3"9" *)
		WP_And_HW_Mode := 5,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"694" #3"9" *)
		WF_And_WP_And_HW_Mode := 6	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"695" #3"9" *)
	);
	Hotwire_PS_Type :
 	(	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"654" #3"14" *)
		Jackle_Type := 0,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"656" #3"9" *)
		Acopian_Type := 1	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"657" #3"9" *)
	);
	Control_Mode :
 	(	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"662" #3"14" *)
		Manual := 0,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"664" #3"9" *)
		Automatic := 1,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"665" #3"9" *)
		FourAxis := 2	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"666" #3"9" *)
	);
	Load_Defaults_Mode :
 	(	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"680" #3"14" *)
		No_Load := 0,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"682" #3"9" *)
		Yes_Load := 1	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"683" #3"9" *)
	);
	Menu_Mode :
 	(	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"670" #3"14" *)
		User := 0,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"672" #3"9" *)
		Boost := 1,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"673" #3"9" *)
		Calibration := 2,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"674" #3"9" *)
		Configuration := 3	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_PowerSupplyDriver/..\GlobDef.h" #2"675" #3"9" *)
	);
END_TYPE
