/********************************************************************
 * COPYRIGHT --  
 ********************************************************************
 * Program: SuperMstr
 * File: SuperDeclaration.h
 * Author: ckaczkowski
 * Created: June 18, 2014
 *******************************************************************/
//#ifndef _SUPERDECLERATION_H
//#define _SUPERDECLERATION_H


#include <bur/plctypes.h>

#include <..\..\Universal\SuperDefinition.h>



typedef enum Project_Enum
{	
	project_None = 0,
	project_HotWire,
	project_FourAxisTig,
	project_US_Orbital,
	project_lastProject,
	
}Project_Enum;

typedef enum Task_Enum
{	
	task_None = 0,
	task__MotorDriv,
	task__PowerSupp,
	task__Master,
	task__Menu,
	task_Main1,

	task_FileOper,
	task_TML_srv,
	task_BR_DC,
	task_AVCprc,
	task_TIG_PSprc,
	task_HW_PSprc,
	task_OSC_TMLprc,
	task_GasCoolPrc,
	task_WIREprc,
	task_WireBlkPrc,
	task_TvlRotPrc,
	task_AVC_SYNCH,
	task_PermSaving,
	task_XMLHelper,	
	task_IndexPrc,	
	task_LincolnPS,
	task_MV,
	task_WRST,

	task_MiscOper,
	task_DC2DirMtr,
	
	task_cJSONTest,
	task_udpserv,
	task_udpApp,
	task_udpclient,
	task_udpsimonly,
	
	task_lastTask,	
	
}Task_Enum;


typedef struct Task_typ
{	
	INT status;
	plcstring Name[32];
	Task_Enum TaskID;
	UDINT st_ident;
	UINT status_id;
	UINT status_inf;
	UINT status_st;
	UINT status_sp;
	USINT state;
	USINT tcnr;
	UINT error;
	
} Task_typ;

typedef struct Project_typ
{	
	 INT status;
	 plcstring Name[32];
	 Task_Enum TaskID[task_lastTask];
	
} Project_typ;


static const  char  PROJECTS_TXT[project_lastProject][21]=
{ 
	{"NONE PROJECT"},
	{"Hotwire"},
	{"FourAxisTIG"},
	{"US Orbital"},
			
};

static const  char  PROJECTS_HRDWR_TXT[project_lastProject][21]=
{ 
	{"unrecognized"},
	{"Hotwire"},
	{"FourAxis"},
	{"US Orbital"},
			
};


_GLOBAL plcstring NewHeadName[64][64];

_GLOBAL UINT Weld_Report_Status , Weld_Report_Mode , Weld_Report_Start_Enable;

_GLOBAL Arc_Link_typ ArcLink;

_GLOBAL  AzzLimScal_typ  LimScal_Tilt;


//Bridge between TML_Srv and UDP_Client
_GLOBAL RS_Channel_typ TML_Msg_Chan[2] , TML_Data_Chan[2] , UDP_Connect_Send[2];
_GLOBAL USINT Kick_TML_Cmd;

_GLOBAL UINT SynchClckFromOsc; // ForeGround Background from OSC
_GLOBAL UINT SynchClckToTIG;  // ForeGround Background generated by TIG freq , and duty param
_GLOBAL UINT SynchClckToTVL;  // ForeGround Background , IN / OUT
_GLOBAL UINT SynchClckToWF;  // ForeGround Background , IN / OUT
_GLOBAL UINT SynchClckToWP;  // ForeGround Background , IN / OUT
_GLOBAL UINT SynchClckToAVC; // Signal F/B to AVC 
_GLOBAL UINT TigSynchMode;
_GLOBAL UINT AVCSynchMode;
_GLOBAL UINT TVLSynchMode;
_GLOBAL UINT WFSynchMode;
_GLOBAL UINT WPSynchMode;

_GLOBAL char Set_AVC_BB_Gain;

_GLOBAL float ABS_TVL_Pos;
_GLOBAL BOOL  Ready2StoreLastPos;;

_GLOBAL TON_typ	CalibrTMR;

_GLOBAL UINT KK_DoNotChangeTMLProgram;

_GLOBAL plcbit KK_TML_PowerON;

_GLOBAL plcbit KK_HomeBtn , KK_StopBtn;
_GLOBAL plcbit STOP_SavingData;
_GLOBAL_RETAIN DINT  OLD_MTR_POS[32] ;//_VAR_RETAIN;
_GLOBAL ParamList_typ ParamList; 
_GLOBAL INT Master_numZone;
_GLOBAL XML_Helper_typ XMLHelper;

//_GLOBAL_RETAIN USINT Use_USB_RAM;
_GLOBAL USINT Use_USB_RAM;

_GLOBAL UINT LCD_Init_Step;
_GLOBAL plcstring curHeadName[64];
_GLOBAL plcstring PLC_Version_TXT[32];

_GLOBAL plcstring UserName[32];
_GLOBAL_RETAIN Project_Enum NextProjectConfig ;//_VAR_RETAIN;
//_GLOBAL Project_Enum NextProj_Padding  _VAR_RETAIN;
_GLOBAL_RETAIN USINT StartOfPermMemObj;//  _VAR_RETAIN;
_GLOBAL_RETAIN USINT EndOfPermMemObj;//  _VAR_RETAIN;

_GLOBAL_RETAIN USINT LastHeadDir ;// _VAR_RETAIN;
_GLOBAL_RETAIN USINT SpareNonPermObjSpace[115];//  _VAR_RETAIN;
//_GLOBAL USINT SpareNonPermObjSpace[116]  _VAR_RETAIN;

//_GLOBAL_RETAIN USINT SparePermObjSpace[156];//  _VAR_RETAIN;
_GLOBAL_RETAIN USINT SparePermObjSpace[156+172];//  _VAR_RETAIN; // obejmuje tez wyrzucony UserValues



_GLOBAL  UINT AVC_Mode;

_GLOBAL_RETAIN DINT NextHeadConfig_Indx;// _VAR_RETAIN; 
_GLOBAL Project_Enum ProjectConfig , ProjectConfig_Hrdw;
_GLOBAL plcbit ProjectConfig_Hrdw_ERROR;
_GLOBAL plcstring ArcLinkPS_IP_Address[16]; 

_GLOBAL Cfg_typ Cfg;
_GLOBAL_RETAIN CurCfg_typ CurCfg; //  _VAR_RETAIN; //
_GLOBAL_RETAIN CurCalib_typ CurCalib;// _VAR_RETAIN; //
_GLOBAL CurCalib_typ DefaultCalib;
_GLOBAL CurMap_typ tmpMap[64];	

_GLOBAL plcstring HMI_lines[20][MAXLOGLEN+1];

_GLOBAL_RETAIN INT curScaledUnitIndx[PARAM_NUM_MAX + VAR_NUM_MAX] ;//_VAR_RETAIN;
//_GLOBAL Scaled_Var_obj ScaledVar[PARAM_NUM_MAX + VAR_NUM_MAX];
_GLOBAL SegmentsTable_obj SegmentsTable;


_GLOBAL FILE_RW_typ File_RW;
_GLOBAL ERROR_Mgr_typ ErrorMgr;

_GLOBAL MASTER_typ Master[2], *pMaster[2];
_GLOBAL HMI_INTRF_typ HMI_Intr;
_GLOBAL plcbit KK_NewHMI;
_GLOBAL PENDANT_HARDWARE_obj Pendant[HRD_COUPLER_NUM] , *pPendant[HRD_COUPLER_NUM];
_GLOBAL HARDWARE_typ Hardware[HRD_COUPLER_NUM];




_GLOBAL SerialPortDriver_typ RS232[2] , *pRS232[2];
_GLOBAL LCD_MGR_obj LCD_MGR[2] , *pLCD_MGR[2];

/// New HMI Drill Down
_GLOBAL DRILL_DWN_MGR_obj DrillDwnHMI;
_GLOBAL SINGLE_EDITOR_MGR_obj SingleParamEditorHMI;
_GLOBAL SINGLE_ENUM_EDITOR SingleEnumParamEditorHMI;


_GLOBAL UINT POPUP_EVENT;


_GLOBAL plcstring ESAB_WebPage[128];



/******************************/

/*** ***************/
_GLOBAL plcbit StopStateMachineEvaluation;

//_GLOBAL Arc_Link_typ ArcLink;

_GLOBAL GEN_MTR_obj DC_Mtr[GEN_MTR_NUM];
_GLOBAL DC2DIRMTR_obj DC2DirMtr[DC2DIRMTR_NUM];
_GLOBAL TML_OUTPUTS_obj TmlRelay[TML_RLY_NUM];


_GLOBAL GenProcess_typ Process[PROCESS_NUM];
_GLOBAL StateVectorProxy_typ VectorStateMach[VECTORS_NUM];
_GLOBAL TML_MGR_typ TML_mgr[TML_MGR_NUM];
_GLOBAL TML_typ TML_MTR_INST[TML_SERVO_NUM] ;
_GLOBAL TML_Axis_typ AxisCh[TML_SERVO_NUM];
_GLOBAL BOOL TML_MTR_CUT_POWER , TML_STOP_SEND_ERROR;

_GLOBAL PS_Param_typ PS_Param_Set[TIG_PS_NUM];
_GLOBAL HW_PS_Param_typ HW_PS_Param_Set[HW_PS_NUM];
_GLOBAL AVC_Param_typ AVC_Param_Set[AVC_NUM];
_GLOBAL OSC_TML_Param_typ OSC_TML_Param_Set[OSC_NUM];
_GLOBAL WRST_TML_Param_typ WRST_TML_Param_Set[WRST_NUM];

_GLOBAL GAS_Param_typ GAS_Param_Set[GAS_NUM];
_GLOBAL GAS_Param_typ COOL_Param_Set[COOL_NUM];
_GLOBAL WIRE_Param_typ WIRE_Param_Set[WIRE_PULS_NUM + WIRE_FEED_NUM];
_GLOBAL WIREBLOCK_Param_typ WR_BLK_Param_Set[WIRE_BLK_NUM];
_GLOBAL TVLROT_Param_typ TVL_ROT_Param_Set[TVL_NUM +ROT_NUM];
_GLOBAL INDEX_Param_typ  INDEX_Param_Set[INDEX_NUM];
_GLOBAL MV_typ MV[MV_NUM];

#ifdef TML_CMD_LOGS
_GLOBAL Cmd_Log_Mgr_typ Cmd_Log_Mgr;
_GLOBAL UINT AxisID_filter;
#endif

_GLOBAL_RETAIN DINT actTicksPerm;// _VAR_RETAIN;

_GLOBAL  HS_obj ReadPermMemory_HS;
_GLOBAL  HS_obj ReadCfgFile_HS;
_GLOBAL  HS_obj Export_HMI_Names_File_HS;

_GLOBAL LOGMGR_obj	LogMgr ;
_GLOBAL_RETAIN UDINT LogID ;//_VAR_RETAIN;
_GLOBAL float CalibrTweakGain ;
_GLOBAL DINT CalibrActDistTicks;

/*
#define DIR_FILELIST_MAX_SIZE 4000
_GLOBAL STRING gDirFileList[DIR_FILELIST_MAX_SIZE];
*/

#define DIR_FILELIST_MAX_SIZE 4000
#define FILE_NAME_MAX 64
plcstring gDirFileList[DIR_FILELIST_MAX_SIZE];
_GLOBAL plcstring gNewFileList[500][64];
_GLOBAL UINT gFileList_Indx;

_GLOBAL float GlobalTimer;

// This is for comunication with other tasks 
_GLOBAL UDINT datagramCountTotal[2];
_GLOBAL UDINT datagramPerSec[2];
_GLOBAL INT PleaseShowFileMessage;


/////   NEW HMI with MIG Pendant

_GLOBAL  SM_obj Screen_sm;
_GLOBAL  SCREEN_obj Screen;

_GLOBAL UINT Virt_Oper_Pend_vis;

_GLOBAL ANDROID_INTRF_typ MIG_PEND_Intrf;
_GLOBAL UINT MIG_PEND_ShowUp_Box_vis;

_GLOBAL unsigned char visPage;
_GLOBAL unsigned char visChangePage;

_GLOBAL UINT NewPageReq_Cmd;
//_GLOBAL EditBox_typ EditBox;

_GLOBAL plcbit Pend_Btn_Stop;
_GLOBAL plcbit Pend_Btn_Left;
_GLOBAL plcbit Pend_Btn_Right;
_GLOBAL plcbit Pend_Btn_Start;


_GLOBAL UINT PageBtnPress[MAX_READ_VAR];
_GLOBAL UINT VarBtnPress[MAX_READ_VAR];
_GLOBAL READ_VAR_typ ReadVar[MAX_READ_VAR];

_GLOBAL UINT VarEnumBtnPress[MAX_READ_VAR];
_GLOBAL READ_ENUM_VAR_typ ReadVar_Enum[MAX_READ_VAR];

_GLOBAL UINT HMI_Jog_Select;
_GLOBAL UINT EditBox_Vis;
_GLOBAL UINT EditBox_Indx;
_GLOBAL UINT Inc_Plus_Btn_Vis;
_GLOBAL UINT Inc_Minus_Btn_Vis; 
_GLOBAL UINT Fwd_Limit_Vis, Rev_Limit_Vis;


////////////////////////////////
///  NEW HMI_M
_GLOBAL LCD_NODE_obj NODES_M[NODES_NUM_MAX];




