TYPE
	PWM_MODULE_STATUS_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1075" #3"16" *)
		UnderVoltageError : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1077" #3"14" *)
		VolatgeWarning : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1078" #3"14" *)
		OverVoltageError : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1079" #3"14" *)
		OvertempeatureError : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1080" #3"14" *)
	END_STRUCT;
	MTR_COMMAND_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1159" #3"16" *)
		command_sm : SM_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1162" #3"16" *)
		Start : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1164" #3"14" *)
		Stop : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1165" #3"14" *)
		Reset : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1166" #3"14" *)
	END_STRUCT;
	SM_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\Statelib.h" #2"21" #3"24" *)
		Step : UDINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\Statelib.h" #2"22" #3"23" *)
		oldStep : UDINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\Statelib.h" #2"23" #3"23" *)
		new : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\Statelib.h" #2"24" #3"24" *)
		ErrorStep : UINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\Statelib.h" #2"25" #3"32" *)
		Tmr1 : TON;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\Statelib.h" #2"26" #3"25" *)
		Text : STRING[51];	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\Statelib.h" #2"27" #3"27" *)
	END_STRUCT;
	PS_MISC_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1227" #3"16" *)
		Ramp : AzzRamp;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1229" #3"21" *)
	END_STRUCT;
	azzslimpid_par : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"110" #3"16" *)
		Y_max : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"111" #3"15" *)
		Y_min : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"112" #3"15" *)
		Kp : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"113" #3"15" *)
		Tn : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"114" #3"15" *)
		Tv : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"115" #3"15" *)
		Kfbk : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"116" #3"15" *)
	END_STRUCT;
	MTR_PARAMETERS_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1171" #3"16" *)
		SpeedSetpoint : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1173" #3"15" *)
		OnRampTime : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1174" #3"15" *)
		OffRampTime : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1175" #3"15" *)
		OnDelayTime : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1176" #3"15" *)
		OffDelayTime : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1177" #3"15" *)
		BoostLevel1SetPoint : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1179" #3"15" *)
		BoostLevel2SetPoint : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1180" #3"15" *)
	END_STRUCT;
	MTR_HARDWARE_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1096" #3"16" *)
		PeriodDurationPWM : UINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1098" #3"14" *)
		PulseWidthPWM : INT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1099" #3"13" *)
		Counter : INT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1100" #3"13" *)
		CurrentMeasurement : INT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1101" #3"13" *)
		PWMError : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1103" #3"14" *)
		CurrentError : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1104" #3"14" *)
		OverCurrentError : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1105" #3"14" *)
		ClearError : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1106" #3"14" *)
		StartCurrentMeasurement : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1108" #3"14" *)
		ResetEncoder : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1111" #3"14" *)
	END_STRUCT;
	MACHINE_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"876" #3"16" *)
		PrimaryPSType : Primary_PS_Type;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"879" #3"25" *)
		HotwirePSType : Hotwire_PS_Type;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"880" #3"25" *)
		ControlMode : Control_Mode;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"881" #3"22" *)
		RunMode : Run_Mode;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"883" #3"18" *)
		LoadDefaultsMode : Load_Defaults_Mode;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"884" #3"28" *)
		Boost1Type : Boost_Type;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"886" #3"16" *)
		Boost2Type : Boost_Type;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"887" #3"16" *)
		ErrorCode : UINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"889" #3"14" *)
		AckErrors : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"890" #3"14" *)
		EditMode : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"892" #3"14" *)
		EstopFault : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"893" #3"14" *)
		BoostLevel1Active : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"896" #3"10" *)
		BoostLevel2Active : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"897" #3"10" *)
		SystemNeedsReset : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"899" #3"10" *)
	END_STRUCT;
	AzzRamp : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"142" #3"16" *)
		x : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"144" #3"15" *)
		dy_up : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"145" #3"15" *)
		dy_down : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"146" #3"15" *)
		y_max : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"147" #3"15" *)
		y_min : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"148" #3"15" *)
		y_set : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"149" #3"15" *)
		status : UINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"151" #3"24" *)
		y : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"152" #3"15" *)
		dt : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"154" #3"15" *)
		y_old : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"155" #3"15" *)
		timestore1 : UDINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"158" #3"23" *)
		enable : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"163" #3"16" *)
		set : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"164" #3"16" *)
		x_reached : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"166" #3"16" *)
		max_limit : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"167" #3"16" *)
		min_limit : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"168" #3"16" *)
	END_STRUCT;
	MENU_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"856" #3"16" *)
		Counter : INT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"858" #3"13" *)
		MenuButton : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"859" #3"14" *)
		LastCounter : INT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"860" #3"13" *)
		Blink : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"861" #3"14" *)
		Edit : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"862" #3"14" *)
		DisplayCode : Display_Setting_Code;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"863" #3"30" *)
		MenuMode : Menu_Mode;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"865" #3"19" *)
		ArcDisplayBlinkEnable : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"867" #3"14" *)
		RemDisplayBlinkEnable : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"868" #3"14" *)
		WfDisplayBlinkEnable : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"869" #3"14" *)
		WpDisplayBlinkEnable : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"870" #3"14" *)
		HwDisplayBlinkEnable : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"871" #3"14" *)
	END_STRUCT;
	AzzPID : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"105" #3"16" *)
		i_sum : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"106" #3"15" *)
		d_old : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"106" #3"22" *)
		e_fbk : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"106" #3"29" *)
		last_time : DINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"107" #3"14" *)
	END_STRUCT;
	PS_COMMAND_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1238" #3"16" *)
		command_sm : SM_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1241" #3"16" *)
		Start : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1243" #3"14" *)
		Stop : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1244" #3"14" *)
		Reset : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1245" #3"14" *)
	END_STRUCT;
	PS_PARAMETERS_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1250" #3"16" *)
		AmpsSetpoint : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1252" #3"15" *)
		OnRampTime : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1253" #3"15" *)
		OffRampTime : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1254" #3"15" *)
		OnDelayTime : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1255" #3"15" *)
		OffDelayTime : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1256" #3"15" *)
		BoostLevel1SetPoint : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1258" #3"15" *)
		BoostLevel2SetPoint : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1259" #3"15" *)
	END_STRUCT;
	PS_HARDWARE_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1205" #3"16" *)
		AnologCommandVoltage : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1208" #3"15" *)
		Enable : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1209" #3"14" *)
	END_STRUCT;
	HARDWARE_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1085" #3"16" *)
		Inputs : ARRAY[0..31] OF BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1087" #3"14" *)
		Outputs : ARRAY[0..11] OF BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1088" #3"14" *)
		AnalogOutputs : ARRAY[0..3] OF INT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1089" #3"13" *)
		AnalogInputs : ARRAY[0..3] OF INT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1090" #3"13" *)
		PWM_Status : PWM_MODULE_STATUS_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1091" #3"31" *)
	END_STRUCT;
	PS_HARDWARE_CONFIG_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1214" #3"16" *)
		CalSlope : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1216" #3"15" *)
		CalOffset : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1217" #3"15" *)
		AmpsPerVoltCommand : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1218" #3"15" *)
		AmpsPerVoltFeedback : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1219" #3"15" *)
	END_STRUCT;
	AzzSlimPID : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"119" #3"16" *)
		W : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"121" #3"15" *)
		X : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"122" #3"15" *)
		request : UDINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"123" #3"23" *)
		pPar : UDINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"124" #3"27" *)
		e : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"126" #3"15" *)
		Y : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"127" #3"15" *)
		dt : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"128" #3"15" *)
		status : UINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"129" #3"24" *)
		addInfo : UINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"130" #3"24" *)
		MovAvgFlt_inst : AzzMovAvgFlt;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"132" #3"26" *)
		PIDTune_inst : AzzPIDTune;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"133" #3"24" *)
		PID_inst : AzzPID;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"134" #3"20" *)
		requ_old : UDINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"135" #3"23" *)
		enable : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"137" #3"16" *)
		enable_old : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"139" #3"16" *)
	END_STRUCT;
	USERVALUES_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1000" #3"16" *)
		WF_Speed : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1004" #3"15" *)
		WP_Freq : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1005" #3"15" *)
		ARC_Amps : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1006" #3"15" *)
		HW_Amps : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1007" #3"15" *)
		WF_Speed_Boost_Level_1 : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1012" #3"11" *)
		WF_Speed_Boost_Level_2 : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1013" #3"11" *)
		WP_Freq_Boost_Level_1 : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1015" #3"15" *)
		WP_Freq_Boost_Level_2 : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1016" #3"15" *)
		ARC_Amps_Boost_Level_1 : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1018" #3"15" *)
		ARC_Amps_Boost_Level_2 : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1019" #3"15" *)
		HW_Amps_Boost_Level_1 : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1021" #3"15" *)
		HW_Amps_Boost_Level_2 : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1022" #3"15" *)
		Boost1Type : Boost_Type;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1024" #3"20" *)
		Boost2Type : Boost_Type;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1025" #3"16" *)
		WF_On_Delay_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1028" #3"11" *)
		WP_On_Delay_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1029" #3"15" *)
		ARC_On_Delay_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1030" #3"15" *)
		HW_On_Delay_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1031" #3"15" *)
		WF_Off_Delay_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1033" #3"15" *)
		WP_Off_Delay_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1034" #3"15" *)
		HW_Off_Delay_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1035" #3"15" *)
		ARC_Off_Delay_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1036" #3"15" *)
		WF_On_Ramp_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1039" #3"11" *)
		WP_On_Ramp_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1040" #3"15" *)
		ARC_On_Ramp_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1041" #3"15" *)
		HW_On_Ramp_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1042" #3"15" *)
		WF_Off_Ramp_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1044" #3"15" *)
		WP_Off_Ramp_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1045" #3"15" *)
		HW_Off_Ramp_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1046" #3"15" *)
		ARC_Off_Ramp_Time : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1047" #3"15" *)
		WF_Speed_Cal_Slope : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1051" #3"15" *)
		WF_Speed_Cal_Offset : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1052" #3"11" *)
		WP_Speed_Cal_Slope : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1054" #3"15" *)
		WP_Speed_Cal_Offset : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1055" #3"11" *)
		ARC_Amps_Cal_Slope : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1057" #3"15" *)
		ARC_Speed_Cal_Offset : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1058" #3"15" *)
		HW_Amps_Cal_Slope : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1060" #3"15" *)
		HW_Speed_Cal_Offset : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1061" #3"15" *)
		PrimaryPSType : Primary_PS_Type;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1064" #3"25" *)
		HotwirePSType : Hotwire_PS_Type;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1065" #3"25" *)
		ControlMode : Control_Mode;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1066" #3"22" *)
		RunMode : Run_Mode;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1067" #3"18" *)
		FirstTimeThrough : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1069" #3"14" *)
	END_STRUCT;
	MTR_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1185" #3"16" *)
		Hardware : MTR_HARDWARE_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1187" #3"26" *)
		Parameters : MTR_PARAMETERS_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1188" #3"28" *)
		Command : MTR_COMMAND_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1189" #3"25" *)
		Misc : MTR_MISC_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1190" #3"22" *)
		HardwareConfig : MTR_HARDWARE_CONFIG_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1192" #3"33" *)
		CurrentVelocity : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1195" #3"15" *)
		CommandVelocity : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1196" #3"15" *)
		Status : UINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1198" #3"14" *)
	END_STRUCT;
	AzzMovAvgFlt : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"79" #3"16" *)
		x : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"81" #3"15" *)
		base : UDINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"82" #3"23" *)
		status : UINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"84" #3"24" *)
		y : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"85" #3"15" *)
		sum_old : LREAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"87" #3"16" *)
		p_xold : UDINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"89" #3"23" *)
		i_xold : UINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"90" #3"24" *)
		base_old : UDINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"91" #3"23" *)
		bootkey_old : UDINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"92" #3"23" *)
		enable : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"94" #3"16" *)
		enable_old : BOOL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"96" #3"16" *)
	END_STRUCT;
	PS_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1264" #3"16" *)
		Hardware : PS_HARDWARE_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1266" #3"25" *)
		Parameters : PS_PARAMETERS_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1267" #3"27" *)
		Command : PS_COMMAND_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1268" #3"24" *)
		Misc : PS_MISC_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1269" #3"21" *)
		HardwareConfig : PS_HARDWARE_CONFIG_obj;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1271" #3"32" *)
		CurrentAmps : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1274" #3"15" *)
		CommandAmps : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1275" #3"15" *)
		Status : UINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1277" #3"14" *)
	END_STRUCT;
	MTR_HARDWARE_CONFIG_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1117" #3"16" *)
		CalSlope : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1120" #3"15" *)
		CalOffset : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1121" #3"15" *)
		EngUnit : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1123" #3"16" *)
		MtrDir : INT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1124" #3"16" *)
		EncDir : INT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1125" #3"16" *)
		CyclesInOvercurrent : UINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1129" #3"14" *)
		CyclesInOvercurrentLimit : UINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1131" #3"14" *)
		CurrentLimit : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1133" #3"15" *)
	END_STRUCT;
	MTR_MISC_obj : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1139" #3"16" *)
		Ramp : AzzRamp;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1142" #3"21" *)
		PID : AzzSlimPID;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1147" #3"24" *)
		PIDParameters : azzslimpid_par;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1148" #3"28" *)
		LastPosition : INT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1150" #3"13" *)
		CurrentPosition : INT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1151" #3"13" *)
		DeltaPosition : DINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"1152" #3"14" *)
	END_STRUCT;
	AzzPIDTune : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"100" #3"16" *)
		nothing : REAL;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\WSI_types.h" #2"101" #3"15" *)
	END_STRUCT;
	bgRingBuffer_typ : STRUCT	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\utilityLib\bgringbuffer.h" #2"23" #3"16" *)
		bufSize : DINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\utilityLib\bgringbuffer.h" #2"25" #3"13" *)
		init : DINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\utilityLib\bgringbuffer.h" #2"26" #3"13" *)
		overrun : DINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\utilityLib\bgringbuffer.h" #2"27" #3"13" *)
		dbgLevel : DINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\utilityLib\bgringbuffer.h" #2"28" #3"13" *)
		dbgFormat : DINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\utilityLib\bgringbuffer.h" #2"29" #3"13" *)
		ptrCircularBufferBegin : UDINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\utilityLib\bgringbuffer.h" #2"31" #3"13" *)
		ptrCircularBufferEnd : UDINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\utilityLib\bgringbuffer.h" #2"32" #3"13" *)
		ptrDataIn : UDINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\utilityLib\bgringbuffer.h" #2"34" #3"13" *)
		ptrDataOut : UDINT;	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\..\Lib\utilityLib\bgringbuffer.h" #2"35" #3"13" *)
	END_STRUCT;
END_TYPE
TYPE
	Primary_PS_Type :
 	(	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"654" #3"14" *)
		Miller_Type := 0,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"656" #3"9" *)
		GTII_Type := 1,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"657" #3"9" *)
		GTVI_Type := 2,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"658" #3"9" *)
		LINCS350_Type := 3,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"659" #3"9" *)
		LINCS500_Type := 4	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"660" #3"9" *)
	);
	Boost_Type :
 	(	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"618" #3"14" *)
		ARC_Boost_Type := 0,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"620" #3"9" *)
		WF_Boost_Type := 1,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"621" #3"9" *)
		WP_Boost_Type := 2,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"622" #3"9" *)
		HW_Boost_Type := 3,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"623" #3"9" *)
		ARC_WF_Boost_Type := 4,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"624" #3"9" *)
		ARC_WP_Boost_Type := 5,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"625" #3"9" *)
		ARC_HW_Boost_Type := 6,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"626" #3"9" *)
		WF_WP_Boost_Type := 7,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"627" #3"9" *)
		WF_HW_Boost_Type := 8,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"628" #3"9" *)
		WP_HW_Boost_Mode := 9,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"629" #3"9" *)
		ARC_WF_WP_Boost_Type := 10,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"630" #3"9" *)
		ARC_WF_HW_Boost_Type := 11,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"631" #3"9" *)
		ARC_WP_HW_Boost_Type := 12,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"632" #3"9" *)
		WF_WP_HW_Boost_Type := 13,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"633" #3"9" *)
		ARC_WF_WP_HW_Boost_Type := 14	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"634" #3"9" *)
	);
	Display_Setting_Code :
 	(	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"502" #3"14" *)
		WpFreq_Setting := 0,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"504" #3"9" *)
		WfSpeed_Setting := 1,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"505" #3"9" *)
		ArcAmps_Setting := 2,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"506" #3"9" *)
		HwAmps_Setting := 3,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"507" #3"9" *)
		BoostLevel_1_Variable_Setting := 4,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"509" #3"9" *)
		ArcAmpsBoostLevel_1_Setting := 5,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"511" #3"9" *)
		WfSpeedBoostLevel_1_Setting := 6,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"512" #3"9" *)
		WpFreqBoostLevel_1_Setting := 7,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"513" #3"9" *)
		HwAmpsBoostLevel_1_Setting := 8,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"514" #3"9" *)
		BoostLevel_2_Variable_Setting := 9,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"516" #3"9" *)
		ArcAmpsBoostLevel_2_Setting := 10,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"518" #3"9" *)
		WfSpeedBoostLevel_2_Setting := 11,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"519" #3"9" *)
		WpFreqBoostLevel_2_Setting := 12,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"520" #3"9" *)
		HwAmpsBoostLevel_2_Setting := 13,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"521" #3"9" *)
		ArcStartDelay_Setting := 14,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"523" #3"9" *)
		WfStartDelay_Setting := 15,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"524" #3"9" *)
		WpStartDelay_Setting := 16,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"525" #3"9" *)
		HwStartDelay_Setting := 17,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"526" #3"9" *)
		ArcStopDelay_Setting := 18,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"528" #3"9" *)
		WfStopDelay_Setting := 19,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"529" #3"9" *)
		WpStopDelay_Setting := 20,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"530" #3"9" *)
		HwStopDelay_Setting := 21,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"531" #3"9" *)
		ArcStartRamp_Setting := 22,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"533" #3"9" *)
		WfStartRamp_Setting := 23,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"534" #3"9" *)
		WpStartRamp_Setting := 24,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"535" #3"9" *)
		HwStartRamp_Setting := 25,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"536" #3"9" *)
		ArcStopRamp_Setting := 26,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"538" #3"9" *)
		WfStopRamp_Setting := 27,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"539" #3"9" *)
		WpStopRamp_Setting := 28,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"540" #3"9" *)
		HwStopRamp_Setting := 29,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"541" #3"9" *)
		ArcCalSlope_Setting := 30,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"543" #3"9" *)
		WfCalSlope_Setting := 31,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"544" #3"9" *)
		HwCalSlope_Setting := 32,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"545" #3"9" *)
		ArcCalOffset_Setting := 33,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"547" #3"9" *)
		WfCalOffset_Setting := 34,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"548" #3"9" *)
		HwCalOffset_Setting := 35,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"549" #3"9" *)
		PrimaryPowerSupplyType_Setting := 36,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"551" #3"9" *)
		HotwirePowerSupplyType_Setting := 37,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"552" #3"9" *)
		ControlMode_Setting := 38,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"553" #3"9" *)
		RunMode_Setting := 39,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"554" #3"9" *)
		LoadDefaults_Setting := 40,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"556" #3"9" *)
		MenuMode_Setting := 41,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"558" #3"9" *)
		ErrorCode_Ack := 42,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"560" #3"9" *)
		PLC_Version := 43,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"562" #3"9" *)
		NEXT_Project_Setting := 44,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"564" #3"9" *)
		Last_Display_Setting_Code := 45	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"566" #3"9" *)
	);
	Run_Mode :
 	(	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"698" #3"14" *)
		WF_Mode := 0,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"700" #3"9" *)
		WP_Mode := 1,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"701" #3"9" *)
		HW_Mode := 2,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"702" #3"9" *)
		WF_And_WP_Mode := 3,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"703" #3"9" *)
		WF_And_HW_Mode := 4,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"704" #3"9" *)
		WP_And_HW_Mode := 5,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"705" #3"9" *)
		WF_And_WP_And_HW_Mode := 6	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"706" #3"9" *)
	);
	Hotwire_PS_Type :
 	(	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"665" #3"14" *)
		Jackle_Type := 0,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"667" #3"9" *)
		Acopian_Type := 1	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"668" #3"9" *)
	);
	Control_Mode :
 	(	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"673" #3"14" *)
		Manual := 0,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"675" #3"9" *)
		Automatic := 1,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"676" #3"9" *)
		FourAxis := 2	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"677" #3"9" *)
	);
	Load_Defaults_Mode :
 	(	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"691" #3"14" *)
		No_Load := 0,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"693" #3"9" *)
		Yes_Load := 1	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"694" #3"9" *)
	);
	Menu_Mode :
 	(	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"681" #3"14" *)
		User := 0,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"683" #3"9" *)
		Boost := 1,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"684" #3"9" *)
		Calibration := 2,	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"685" #3"9" *)
		Configuration := 3	(* #1"C:/projects/UnivCntrl/UniversalController/Logical/HotWire/_MotorDriver/..\GlobDef.h" #2"686" #3"9" *)
	);
END_TYPE
